#!/bin/sh
# General variables
GREEN='\033[0;32m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color
SEPERATOR="${WHITE}----------------------------------------------------------------${NC}"

# Project related variables
PREFIX="${GREEN}[Npm Toolbox]${WHITE}"

# Important configs
CONTAINER="npm-tools"
#DNS_SERVER=${DNS_SERVER:="127.0.0.1"}

# Define base dir of script
BASEDIR="$( cd "$(dirname "$0")" ; pwd -P )"

PORT=${PORT:="3000"}
INTERACTIVE=${INTERACTIVE:="-it"}

# Commands
key="$1"
if [ $1 ]
    then
        shift
fi

WORKSPACE_ROOT="docker run --name npm-tools-bash --user=root -i -t --rm $CONTAINER"
WORKSPACE_RUN="docker run --name npm-tools-$key-$(date "+%Y.%m.%d-%H.%M.%S"|base32) $INTERACTIVE --user=$UID:$GID -p $PORT:$PORT  -v $PWD:/tmp/ --rm $CONTAINER"

case $key in
    fap)
        flags=$@
        echo "${PREFIX} Build container: $CONTAINER ...${NC}"
        docker build $flags -t npm-tools .
    ;;
    -s|ssh|bash)
        echo "${PREFIX} Connect to $CONTAINER container...${NC}"
        $WORKSPACE_ROOT bash -l
        ;;

    *)
        echo "${PREFIX} Run command: $key with $@"
        $WORKSPACE_RUN $key $@
        ;;
esac
