name: Build docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t npm-tools .
    - name: Test container methods
      run: |
        INTERACTIVE=" " ./wanker npm -v
        INTERACTIVE=" " ./wanker vue -V
