name: Build docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./wanker fap
    - name: Test container methods
      run: |
        ./wanker npm -v
        ./wanker vue -V
      env:
        INTERACTIVE: " "
